CREATE DATABASE `sp` /*!40100 DEFAULT CHARACTER SET utf8 */

CREATE TABLE `hotel_record` (
  `name` varchar(50) DEFAULT NULL,
  `cardno` varchar(100) DEFAULT NULL,
  `descriot` varchar(100) DEFAULT NULL,
  `ctftp` varchar(100) DEFAULT NULL,
  `ctfid` varchar(100) DEFAULT NULL,
  `gender` varchar(100) DEFAULT NULL,
  `birthday` varchar(100) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `zip` varchar(50) DEFAULT NULL,
  `dirty` varchar(50) DEFAULT NULL,
  `distinct1` varchar(255) DEFAULT NULL,
  `distinct2` varchar(255) DEFAULT NULL,
  `distinct3` varchar(255) DEFAULT NULL,
  `distinct4` varchar(255) DEFAULT NULL,
  `distinct5` varchar(255) DEFAULT NULL,
  `distinct6` varchar(255) DEFAULT NULL,
  `firstnm` varchar(255) DEFAULT NULL,
  `lastnm` varchar(255) DEFAULT NULL,
  `duty` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `tel` varchar(255) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `nation` varchar(255) DEFAULT NULL,
  `taste` varchar(255) DEFAULT NULL,
  `education` varchar(255) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `ctel` varchar(255) DEFAULT NULL,
  `caddress` varchar(255) DEFAULT NULL,
  `czip` varchar(255) DEFAULT NULL,
  `family` varchar(255) DEFAULT NULL,
  `version` varchar(255) DEFAULT NULL,
  `id` varchar(255) DEFAULT NULL,
  `is_delete` tinyint(4) DEFAULT '0',
  KEY `idx_name` (`name`),
  KEY `idx_ctfid` (`ctfid`),
  KEY `idx_birthday` (`birthday`),
  KEY `idx_tel` (`tel`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_add` (`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
