CREATE TABLE `jd_book` (
  `id` varchar(50) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `brand` varchar(50) DEFAULT NULL,
  `vendor` varchar(50) DEFAULT NULL,
  `promotion` varchar(100) DEFAULT NULL,
  `adword` varchar(50) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `c1` varchar(20) DEFAULT NULL,
  `c2` varchar(20) DEFAULT NULL,
  `c3` varchar(20) DEFAULT NULL,
  `selling_price` varchar(10) DEFAULT NULL,
  `market_price` varchar(10) DEFAULT NULL,
  `discount` varchar(10) DEFAULT NULL,
  `page_url` varchar(255) DEFAULT NULL,
  `img_primary` varchar(255) DEFAULT NULL,
  `comments_num` varchar(10) DEFAULT NULL,
  `thumbs_num` varchar(10) DEFAULT NULL,
  KEY `idx_pid` (`id`),
  KEY `idx_c1` (`c1`),
  KEY `idx_c2` (`c2`),
  KEY `idx_c3` (`c3`),
  KEY `idx_title` (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
